### ISSUE TITLE
is this on windows

### ISSUE THREAD

**Issue by Robthekilla** [Slord6/MC-Fren#6]
can i use it on windows i get error ''The system cannot find the file specified''

**Comment by Slord6** [comment]
Hi, yes - I developed it on Windows. Is there more detail in the error message?

A stack trace or console output would be most useful

**Comment by Robthekilla** [comment]
![image](https://user-images.githubusercontent.com/91676282/157378082-9831443d-7de1-4c38-b909-276439422463.png)

**Comment by Slord6** [comment]
Can you run `dir` in the same place and report the output?

**Comment by Robthekilla** [comment]
how?

**Comment by Slord6** [comment]
In a command prompt, in the same way you were running three other command

**Comment by Robthekilla** [comment]
i got it working but how do i get mojang/microsoft accounts instead of cracked

**Comment by Robthekilla** [comment]
like real accounts not cracked

**Comment by Robthekilla** [comment]
it doesnt work it doesnt join localhost

**Comment by Slord6** [comment]
> i got it working but how do i get mojang/microsoft accounts instead of cracked

> it doesnt work it doesnt join localhost

This is very little information to go on. But I think if I understand your issue:

If you're trying to join a session hosted by opening a single player world to LAN, then that acts the same as a 'online' hosted server and will probably fail to log in the bot, because it doesn't have a real account - it acts similarly to a 'cracked' account, as you mentioned.

To solve this you will need to host a local server - there are thousands of tutorials showing you how - and then once setup change the `server.properties` file to have `online-mode` set to `false`. [This site ](https://help.akliz.net/docs/edit-serverproperties#online-mode) covers doing that.

I've not tested trying to login with a full Mojang account, because I only have one account and you can only login to a server once per user account, so you wouldn't be able to see the bot if it logged in with your own credentials. It might be possible, but it's not a priority to add that functionality.

**Comment by Robthekilla** [comment]
can you try to add it make a aternos server and use your account and check if it joined pls

**Comment by Slord6** [comment]
[Apparently](https://board.aternos.org/thread/16104-online-offline-mode/) you can set Aternos servers to allow cracked clients.

 >Normally your server is in online mode.
>As soon as you enable cracked on https://aternos.org/options your server will be set to offline mode.

Then you should be able to connect as any username

**Comment by Robthekilla** [comment]
no i want to try on anarchy servers

**Comment by Robthekilla** [comment]
it shows this when i try to use 
![image](https://user-images.githubusercontent.com/91676282/157869574-caf2b20d-a209-4e70-8488-ead973e6653d.png)

**Comment by Robthekilla** [comment]
i pressed enter and it stays same

**Comment by Slord6** [comment]
Anarchy servers will probably have online mode set to false already and if not the bot in its current state won't work.

The output when a bot spawns should be `<bot username> initalised`. If you don't see that then the bot never connects. I'd recommend trying it locally so you are used to normal operation before trying it against an online server. This would also flag any potential firewall issues.

> it shows this when i try to use ![image](https://user-images.githubusercontent.com/91676282/157869574-caf2b20d-a209-4e70-8488-ead973e6653d.png)


If that is your actual password for minecraft I'd very strongly recommend you reset it before someone steals your account - these comments are public.
Also, please post single comments rather than 3-4 in a row.

**Comment by Robthekilla** [comment]
no thats the default password in your thing

**Comment by Slord6** [comment]
@Robthekilla was there anything else or can I close this issue?

**Comment by Robthekilla** [comment]
I still can’t get it to work

**Comment by Robthekilla** [comment]
Got discord?

**Comment by Slord6** [comment]
Have you tried hosting a local server?

I'd rather not use discord - others wouldn't have access to the eventual solution
